pipeline:
  eth:
    group: deploy
    image: appleboy/drone-scp
    host: eth.minerpool.co
    username: ubuntu
    key: ${SSH_KEY}
    secrets: [ SSH_KEY ]
    target: /mnt/open-ethereum-pool-master/
    source: eth_*.json

  etc:
    group: deploy
    image: appleboy/drone-scp
    host: etc.minerpool.co
    username: ubuntu
    key: ${SSH_KEY}
    secrets: [ SSH_KEY ]
    target: /mnt/open-ethereum-pool-master/
    source: etc_*.json

  dbix:
    group: deploy
    image: appleboy/drone-scp
    host: dbix.minerpool.co
    username: ubuntu
    key: ${SSH_KEY}
    secrets: [ SSH_KEY ]
    target: /mnt/open-ethereum-pool-master/
    source: dbix_*.json

  restart:
    group: deploy
    image: appleboy/drone-ssh
    host:
      - eth.minerpool.co
      - etc.minerpool.co
      - dbix.minerpool.co
    username: ubuntu
    key: ${SSH_KEY}
    secrets: [ SSH_KEY ]
    script:
      - sleep 10 && sudo /bin/systemctl restart oepool oeapi oepayout oeunlock
