pipeline:
    ##  etc:
#    image: appleboy/drone-scp
#    host: etc.minerpool.co
#    username: ubuntu
#    key: ${SSH_KEY}
#    target: /mnt/open-ethereum-pool-master/config.json
#    source: config_etc.json

  restart:
    image: appleboy/drone-ssh
    host:
      - eth.minerpool.co
      - etc.minerpool.co
      - dbix.minerpool.co
    username: ubuntu
    key: ${SSH_KEY}
    secrets: [ SSH_KEY ]
    script:
      - /bin/systemctl restart oepool
